python_tests(
    runtime_binary_dependencies = [
        "src/python/arcor2/scripts:upload_builtin_objects",
        "src/python/arcor2_mocks/scripts:mock_project",
        "src/python/arcor2_mocks/scripts:mock_scene",
        "src/python/arcor2_build/scripts:build",
        "src/python/arcor2_execution/scripts:execution",
        "src/python/arcor2_arserver/scripts:arserver"
    ]
)