python_tests(
    runtime_package_dependencies=[
        "src/python/arcor2_object_types/scripts:upload_object_types",
        "src/python/arcor2_storage/scripts:storage",
        "src/python/arcor2_scene/scripts:scene",
        "src/python/arcor2_build/scripts:build",
        "src/python/arcor2_execution/scripts:execution",
        "src/python/arcor2_arserver/scripts:arserver",
    ],
)

python_test_utils(name="test_utils", sources=["conftest.py", "testutils.py"])
