python_tests(
    interpreter_constraints=["==3.12.*"],
    runtime_package_dependencies=[
        "src/python/arcor2_dobot/scripts:dobot",
        "src/python/arcor2_scene/scripts:scene",
    ],
)

python_test_utils(name="test_utils")
