python_tests(
    runtime_package_dependencies=[
        "src/python/arcor2_dobot/scripts:dobot",
        "src/python/arcor2_scene/scripts:scene",
        "src/python/arcor2_runtime",
        "src/python/arcor2_execution_data",
    ],
)

python_test_utils(name="test_utils")
