version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/src/docker/*"
    schedule:
      interval: "daily"
    groups:
      docker-base-images:
        group-by: dependency-name
  - package-ecosystem: "docker-compose"
    directories:
      - "/compose-files/*"
    schedule:
      interval: "daily"
    groups:
      compose-images:
        group-by: dependency-name
