version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/src/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker-compose"
    directory: "/compose-files"
    schedule:
      interval: "daily"