services:
  fanuc-demo-arserver:
    image: arcor2/arcor2_arserver:1.2.0
    container_name: fanuc-demo-arserver
    depends_on:
      - fanuc-demo-project
      - fanuc-demo-build
      - fanuc-demo-execution
      - fanuc-demo-scene
      - fanuc-demo-calibration
      - fanuc-demo-robot
    ports:
      - "6789:6789"
      - "6799:6799"
    networks:
          - fanuc-demo-scene-network
          - fanuc-demo-project-network
          - fanuc-demo-asset-network
          - fanuc-demo-calibration-network
          - fanuc-demo-robot-network
    environment:
      - ARCOR2_PROJECT_SERVICE_URL=http://fanuc-demo-project:10000
      - ARCOR2_ASSET_SERVICE_URL=http://fanuc-demo-asset:10040
      - ARCOR2_SCENE_SERVICE_URL=http://fanuc-demo-scene:5013
      - ARCOR2_EXECUTION_URL=ws://fanuc-demo-execution:6790
      - ARCOR2_BUILD_URL=http://fanuc-demo-build:5008
      - ARCOR2_CALIBRATION_URL=http://fanuc-demo-calibration:5014

  fanuc-demo-build:
    image: arcor2/arcor2_build:1.4.0
    container_name: fanuc-demo-build
    depends_on:
      - fanuc-demo-project
    environment:
      - ARCOR2_PROJECT_SERVICE_URL=http://fanuc-demo-project:10000
      - ARCOR2_PROJECT_PATH=""
    ports:
      - "5008:5008"
    networks:           
      - fanuc-demo-project-network

  fanuc-demo-execution:
    image: arcor2/arcor2_execution:1.3.0
    container_name: fanuc-demo-execution
    networks:
      - fanuc-demo-execution-network
      - fanuc-demo-scene-network
      - fanuc-demo-robot-network
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://fanuc-demo-scene:5013
      - ARCOR2_PROJECT_PATH=/root/project
    volumes:
        - fanuc-demo-execution:/root/project

  fanuc-demo-robot:
    image: arcor2/arcor2_fanuc:0.4.0
    container_name: fanuc-demo-robot
    restart: on-failure:3  # TODO it often fails to contact Scene Service when starting, remove once we have healthcheck
    depends_on:
      - fanuc-demo-scene
    networks:
      - fanuc-demo-robot
      - fanuc-demo-scene-network
    ports:
        - "5027:5027"
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://fanuc-demo-scene:5013

  fanuc-demo-calibration:
    image: arcor2/arcor2_calibration:1.2.0
    networks:
      - fanuc-demo-calibration-network
    ports:
      - "5014:5014"
    environment:
      - ARCOR2_CALIBRATION_URL=http://fanuc-demo-calibration:5014
      - ARCOR2_CALIBRATION_MOCK=false
    volumes:
      - ./calibration.yaml:/root/calibration.yaml

  fanuc-demo-scene:
    image: arcor2/arcor2_scene:1.1.0
    container_name: fanuc-demo-scene
    networks:
      - fanuc-demo-scene-network
    ports:
      - "5013:5013"

  fanuc-demo-asset:
    image: registry.gitlab.com/kinalisoft/test-it-off/asset:1.0.0
    container_name: "fanuc-demo-asset"
    environment:
        - "ASSETS_FOLDER=/tmp/asset"
    volumes:
        - fanuc-demo-asset:/tmp/asset
    networks:
        - fanuc-demo-asset-network
    expose:
        - "10040"
    ports:
        - "10040:10040"

  fanuc-demo-project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project:1.0.1
    container_name: "fanuc-demo-project"
    ports:
      - "10000-10001:10000-10001"
    environment:
      - "ASSET_SERVICE_URL=http://fanuc-demo-asset:10040"
    depends_on:
      - fanuc-demo-asset
    networks:
      - fanuc-demo-project-network
      - fanuc-demo-asset-network

  fanuc-demo-nginx:
    image: nginx:1.25.4
    container_name: "fanuc-demo-nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "6790:80"
    networks:
      - fanuc-demo-project-network
    depends_on:
      - fanuc-demo-project

  fanuc-demo-upload-object-types:
    image: arcor2/arcor2_fanuc_upload_object_types:0.4.0
    container_name: "fanuc-demo-upload-object-types"
    depends_on:
      - fanuc-demo-project
    networks:
      - fanuc-demo-project-network
      - fanuc-demo-asset-network
    environment:
      - ARCOR2_PROJECT_SERVICE_URL=http://fanuc-demo-project:10000
      - ARCOR2_ASSET_SERVICE_URL=http://fanuc-demo-asset:10040


volumes:
  fanuc-demo-asset:
  fanuc-demo-execution:

networks:
  fanuc-demo-scene-network:
  fanuc-demo-execution-network:
  fanuc-demo-asset-network:
  fanuc-demo-project-network:
  fanuc-demo-robot-network:
  fanuc-demo-calibration-network:
  fanuc-demo-robot: