resources(
    name="moveit_yaml",
    sources=["moveit.yaml"],
)

resources(
    name="urdf_assets",
    sources=[
        "urdf/ur5e.urdf",
        "urdf/ur5e.srdf",
        "urdf/meshes/ur5e/collision/*.stl",
        "urdf/meshes/ur5e/visual/*.dae",
    ],
)