arcor2_python_distribution(
    name="arcor2_execution_rest_proxy",
    description="REST Proxy for ARCOR2 Execution service.",
    binaries=
        {
            "arcor2_execution_rest_proxy": "src/python/arcor2_execution_rest_proxy/scripts:execution_rest_proxy"
            }
)