arcor2_python_distribution(
    name="arcor2_mocks",
    description="Mocks for services developed by Kinali.",
    binaries={
        "arcor2_mock_project": "src/python/arcor2_mocks/scripts:mock_project",
        "arcor2_mock_scene": "src/python/arcor2_mocks/scripts:mock_scene"
        }
)