arcor2_python_distribution(
    name="arcor2_object_types",
    description="ARCOR2 object types and built-in actions bundle.",
    binaries={"arcor2_upload_object_types": "src/python/arcor2_object_types/scripts:upload_object_types"},
    dependencies=[
        "src/python/arcor2_object_types/parameter_plugins",
    ],
)
