python_sources()

arcor2_pex_binary(name="body_part_moving")
arcor2_pex_binary(name="body_part_nearby")
arcor2_pex_binary(name="user_present")
arcor2_pex_binary(name="body_count")
arcor2_pex_binary(name="collision")
