python_sources()

arcor2_pex_binary(
    name = "upload_objects",
    dependencies = [
        "src/python/arcor2_fit_demo/data/dobot-m1",
        "src/python/arcor2_fit_demo/data/dobot-magician",
        "src/python/arcor2_fit_demo/data:kinect_azure.dae",
        "src/python/arcor2_fit_demo/data:conveyor_belt.dae"]
)