arcor2_python_distribution(
    name="arcor2_3d_mouse",
    description="ARCOR2 library for manipulation with 3D mouse",
    binaries={"arcor2_3d_mouse": "src/python/arcor2_3d_mouse/scripts:mouse_launcher"},
)
