arcor2_python_distribution(
    name="arcor2_kinect_azure_data",
    description="ARCOR2 Kinect Azure data",
    binaries={"arcor2_kinect_azure_data": "src/python/arcor2_kinect_azure_data/object_types:kinect_azure"},
)
