python_binary(
    name = "mock_project",
    sources = ["project.py"],
    entry_point = "arcor2_mocks.scripts.project"
)

python_binary(
    name = "mock_scene",
    sources = ["scene.py"],
    entry_point = "arcor2_mocks.scripts.scene"
)