pex_binary(
    name = "mock_project",
    sources = ["project.py"],
    dependencies = ["3rdparty:PyYAML"],
    entry_point = "arcor2_mocks.scripts.project:main",
    zip_safe=False
)

pex_binary(
    name = "mock_scene",
    sources = ["scene.py"],
    dependencies = ["3rdparty:PyYAML"],
    entry_point = "arcor2_mocks.scripts.scene:main",
    zip_safe=False
)