ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2:arcor2_dist \
	&& ./pants package src/python/arcor2_arserver:arcor2_arserver_dist \
	&& ./pants package src/python/arcor2_arserver_data:arcor2_arserver_data_dist \
	&& ./pants package src/python/arcor2_build:arcor2_build_dist \
	&& ./pants package src/python/arcor2_build_data:arcor2_build_data_dist \
	&& ./pants package src/python/arcor2_calibration:arcor2_calibration_dist \
	&& ./pants package src/python/arcor2_calibration_data:arcor2_calibration_data_dist \
	&& ./pants package src/python/arcor2_execution:arcor2_execution_dist \
	&& ./pants package src/python/arcor2_execution_data:arcor2_execution_data_dist \
	&& ./pants package src/python/arcor2_execution_rest_proxy:arcor2_execution_rest_proxy_dist \
	&& ./pants package src/python/arcor2_fit_demo:arcor2_fit_demo_dist \
	&& ./pants package src/python/arcor2_kinali:arcor2_kinali_dist \
	&& ./pants package src/python/arcor2_mocks:arcor2_mocks_dist

# RUN cd ~/arcor2 \
#    && ./build-support/setup-venv.sh

# For some reason this does not work, the error is:
# Error: [Errno 2] No such file or directory: '/root/arcor2/build-support/.venv/bin/python3.8
# RUN source build-support/.venv/bin/activate

RUN cd ~/arcor2/dist \
	&& pip3 install -e ./arcor2-`cat ../src/python/arcor2/VERSION` \
    && pip3 install -e ./arcor2_calibration_data-`cat ../src/python/arcor2_calibration_data/VERSION` \
	&& pip3 install -e ./arcor2_arserver_data-`cat ../src/python/arcor2/VERSION` \
	&& pip3 install -e ./arcor2_build_data-`cat ../src/python/arcor2_build_data/VERSION` \
	&& pip3 install -e ./arcor2_execution_data-`cat ../src/python/arcor2_execution_data/VERSION` \
	&& pip3 install -e ./arcor2_arserver-`cat ../src/python/arcor2_arserver/VERSION` \
	&& pip3 install -e ./arcor2_build-`cat ../src/python/arcor2_build/VERSION` \
	&& pip3 install -e ./arcor2_calibration-`cat ../src/python/arcor2_calibration/VERSION` \
	&& pip3 install -e ./arcor2_execution-`cat ../src/python/arcor2_execution/VERSION` \
	&& pip3 install -e ./arcor2_execution_rest_proxy-`cat ../src/python/arcor2_execution_rest_proxy/VERSION` \
	&& pip3 install -e ./arcor2_fit_demo-`cat ../src/python/arcor2_fit_demo/VERSION` \
	&& pip3 install -e ./arcor2_kinali-`cat ../src/python/arcor2_kinali/VERSION` \
	&& pip3 install -e ./arcor2_mocks-`cat ../src/python/arcor2_mocks/VERSION`