ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2/scripts:upload_builtin_objects

FROM arcor2/arcor2_dist_base:$version

COPY --from=0 /root/arcor2/dist/src.python.arcor2.scripts/upload_builtin_objects.pex /root/upload_objects.pex

CMD ["python", "/root/upload_objects.pex"]
