ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2_kinect_azure/scripts:kinect_azure

FROM arcor2/arcor2_dist_base:$version

COPY --from=0 /root/arcor2/dist/src.python.arcor2_kinect_azure.scripts/kinect_azure.pex /root/kinect_azure.pex

RUN apt-get update \
	&& apt-get install -y -q libgl1-mesa-glx libglib2.0-0

COPY docker/start-kinect-azure.sh ./start.sh

