ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2_build/scripts:build

FROM arcor2/arcor2_dist_base:$version

COPY --from=0 /root/arcor2/dist/src.python.arcor2_build.scripts/build.pex /root/build.pex

COPY docker/start-build.sh ./start.sh