ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants binary src/python/arcor2_kinali/scripts:upload_objects

FROM arcor2/arcor2_dist_base:$version

COPY --from=0 /root/arcor2/dist/src.python.arcor2_kinali.scripts/upload_objects.pex /root/upload_objects.pex

CMD ["python", "/root/upload_objects.pex"] 