ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2_execution/scripts:execution

FROM arcor2/arcor2_dist_base:$version

RUN mkdir -p /root/project

COPY --from=0 /root/arcor2/dist/src.python.arcor2_execution.scripts/execution.pex /root/execution.pex

COPY docker/start-execution.sh ./start.sh