ARG version
FROM python:$version

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
  git \
  && rm -rf /var/lib/apt/lists/*

ENV PYTHONOPTIMIZE=1
CMD ["/bin/sh", "/start.sh"]
