FROM ubuntu:20.04


RUN apt-get update \
  && apt-get install --yes \
  curl \
  build-essential \
  git \
  python3.8 \
  python3.8-dev \
  python3-distutils \
  unzip

RUN curl \
  --silent \
  --location \
  https://bootstrap.pypa.io/get-pip.py \
  --output /tmp/get-pip.py \
  && python3.8 /tmp/get-pip.py

RUN pip install \
  pants \
  pipenv

RUN apt-get update \
    && apt-get install -y 


