ARG version
FROM ubuntu:$version

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
  && apt-get update \ 
  && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
  curl \
  build-essential \
  git \
  python3.9 \
  python3.9-venv \
  python3.9-dev \
  python3-distutils \
  python3-pip \
  unzip

RUN pip3 install --upgrade \
  pip

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants --version

RUN apt-get install -y -q --no-install-recommends gnupg2 \
    && cd ~/arcor2 \
    && ./build-support/install_kinect_prerequisites.sh
