ARG version=latest
FROM arcor2/arcor2_base:$version

COPY . /root/arcor2/

RUN cd ~/arcor2 \
	&& ./pants package src/python/arcor2_mocks/scripts:mock_project \
	&& ./pants package src/python/arcor2_mocks/scripts:mock_scene

FROM arcor2/arcor2_dist_base:$version

# needed because of Open3D
RUN apt-get update \
    && apt-get install -y libgl1-mesa-glx libglib2.0-0 libgomp1 libusb-1.0-0

COPY --from=0 /root/arcor2/dist/src.python.arcor2_mocks.scripts/mock_project.pex /root/mock_project.pex
COPY --from=0 /root/arcor2/dist/src.python.arcor2_mocks.scripts/mock_scene.pex /root/mock_scene.pex

COPY docker/start-mocks.sh ./start.sh