arcor2_python_distribution(
    name="arcor2_calibration",
    description="ARCOR2 Calibration",
    binaries=
        {
            "arcor2_calibration": "src/python/arcor2_calibration/scripts:calibration"
            }
)