python_tests(
    runtime_package_dependencies = [
        "src/python/arcor2_kinali/scripts:upload_objects",
        "src/python/arcor2_mocks/scripts:mock_project",
        "src/python/arcor2_execution/scripts:execution",
        "src/python/arcor2_arserver/scripts:arserver"
    ]
)