python_sources()

arcor2_pex_binary(name="cube_detector")

arcor2_pex_binary(name="gui_cube_detector", dependencies=["src/python/arcor2_cube_detector/data/dataset"])

arcor2_pex_binary(name="dataset_evaluation", dependencies=["src/python/arcor2_cube_detector/data/dataset"])
