python_binary(
    name = "arserver",
    sources = ["arserver.py"],
    entry_point = "arcor2_arserver.scripts.arserver"
)

python_binary(
    name = "broadcaster",
    sources = ["broadcaster.py"],
    entry_point = "arcor2_arserver.scripts.broadcaster"
)