python_tests(
    runtime_package_dependencies = [
        "src/python/arcor2_execution_rest_proxy/scripts:execution_rest_proxy",
    ],
    dependencies = ["3rdparty:setuptools"],  # https://github.com/p1c2u/openapi-spec-validator/issues/133
)