arcor2_python_distribution(
    name="arcor2_kinect_azure",
    description="REST API for Kinect Azure.",
    binaries={
            "arcor2_kinect_azure": "src/python/arcor2_kinect_azure/scripts:kinect_azure"
            }
)