python_sources()

arcor2_pex_binary(
    name="kinect_azure",
    dependencies=[
        "src/python/arcor2_kinect_azure_data",
        "src/python/arcor2_kinect_azure_data/data:kinect_azure.dae",
    ],
)
