arcor2_python_distribution(
    name="arcor2_fit_demo",
    description="ARCOR2 FIT Demo",
    binaries=
        {
            "arcor2_fit_demo_upload_objects": "src/python/arcor2_fit_demo/scripts:upload_objects"
            }
)