python_tests(
    interpreter_constraints=["==3.12.*"],
    dependencies=[
        "src/python/arcor2_fit_demo/data/dobot-m1:dobot-m1",
        "src/python/arcor2_fit_demo/data/dobot-magician:dobot-magician",
    ],
)
