python_tests(
    dependencies=["3rdparty#PyYAML"],
    runtime_package_dependencies=[
        "src/python/arcor2_ur/scripts:ur", "src/python/arcor2_ur/scripts:robot_publisher",
    ],
)

python_test_utils(name="test_utils")
