python_tests(
    runtime_package_dependencies=[
        "src/python/arcor2_ur/scripts:ur", "src/python/arcor2_ur/scripts:robot_publisher",
    ],
    interpreter_constraints=["==3.12.*"],
)

python_test_utils(name="test_utils")