python_sources()

arcor2_pex_binary(
    name="kinect_azure",
    dependencies=[
        "src/python/arcor2_kinect_azure",
        "src/python/arcor2_kinect_azure/data",
        "src/python/arcor2_kinect_azure_data",
    ],
)

arcor2_pex_binary(name="kinect_viewer")
