arcor2_python_distribution(
    name="arcor2_arserver",
    description="ARCOR2 ARServer",
    dependencies=[
        "src/python/arcor2_arserver/clients",
        "src/python/arcor2_arserver/object_types",
        "src/python/arcor2_arserver/rpc"
    ],
    binaries=
        {
            "arcor2_arserver": "src/python/arcor2_arserver/scripts:arserver",
            "arcor2_broadcaster": "src/python/arcor2_arserver/scripts:broadcaster"
            }
)