version: '3'

services:
  fit-demo-dobot-magician:
    environment:
      - ARCOR2_DOBOT_MOCK=false
    devices:
      - /dev/dobotMagician:/dev/dobot

  fit-demo-dobot-m1:
    environment:
      - ARCOR2_DOBOT_MOCK=false
    devices:
      - /dev/dobotM1:/dev/dobot