arcor2_python_distribution(
    name="arcor2",
    description="ARCOR2 base library",
    dependencies=[
        "src/python/arcor2/data",
        "src/python/arcor2/data/rpc",
        "src/python/arcor2/exceptions",
        "src/python/arcor2/source",
    ]
)
