arcor2_python_distribution(
    name="arcor2_kinali",
    description="ARCOR2 integration for Kinali services.",
    binaries={
            "arcor2_kinali_upload_objects": "src/python/arcor2_kinali/scripts:upload_objects"
            }
)