python_tests(
    runtime_package_dependencies = [
        "src/python/arcor2_mocks/scripts:mock_project",
        "src/python/arcor2_mocks/scripts:mock_scene",
    ],
    dependencies = ["3rdparty:setuptools"],  # https://github.com/p1c2u/openapi-spec-validator/issues/133
)