python_tests(
    name="test_asset.py",
    runtime_package_dependencies=["src/python/arcor2_mocks/scripts:mock_asset"],
    sources=["test_asset.py"],
)

python_tests(
    name="test_project.py",
    runtime_package_dependencies=["src/python/arcor2_mocks/scripts:mock_project"],
    sources=["test_project.py"],
)