arcor2_python_distribution(
    name="arcor2_build",
    description="ARCOR2 Build",
    dependencies=[
        "src/python/arcor2_build/source"
    ],
    binaries={
        "arcor2_build": "src/python/arcor2_build/scripts:build"
        }
)