arcor2_python_distribution(
    name="arcor2_arserver_data",
    description="ARCOR2 ARServer data",
    dependencies=[
        "src/python/arcor2_arserver_data/events",
        "src/python/arcor2_arserver_data/rpc"
    ]
)