services:
  ur-demo-robot-api:
    environment:
      - ARCOR2_UR_ROBOT_IP=192.168.80.2
    volumes:
      - ./robot_calibration.yaml:/root/robot_calibration.yaml
    network_mode: "host"  # ObjectType has to connect to localhost:5012