services:
  ur-demo-ursim:
    image: universalrobots/ursim_e-series:5.17.3  # version should match version of the Polyscope on the robot
    container_name: ur-demo-ursim
    ports:  # network_mode: host can't be (easily) used as ursim starts its own X server
      - "5900:5900"  # VNC port
      - "6080:6080"  # web VNC
#      - "30001:30001"
#      - "30002:30002"
#      - "30004:30004"
#      - "29999:29999"
    networks:
      - ur-demo-network
    environment:
      - ROBOT_MODEL=UR5
    volumes:
      - ursim-gui-cache:/ursim/GUI
      - urcap-build-cache:/ursim/.urcaps
      - ursim-programs:/ursim/programs
  ur-demo-robot-api:
    environment:
      - ARCOR2_UR_ROBOT_IP=ur-demo-ursim
      - ARCOR2_UR_STARTUP_SLEEP=10
    networks:
      - ur-demo-network  # ObjectType has to connect to ur-demo-ursim:5012

volumes:
  ursim-gui-cache:
  urcap-build-cache:
  ursim-programs: