#!/usr/bin/env python3

"""An example of the main script where its structure is generated by the Build
service for the specific project."""

from arcor2.data.common import uid
from arcor2.exceptions.runtime import print_exception
from arcor2.resources import ResourcesBase
from arcor2_kinali.object_types.abstract_simple import Settings as SimpleSettings
from arcor2_kinali.object_types.statistic import Statistic


class Resources(ResourcesBase):
    """Within the execution package, this is generated by the Build service and
    placed in resources.py."""

    def __init__(self) -> None:
        super(Resources, self).__init__("project_uuid")


def main(res: Resources) -> None:

    statistic = Statistic(uid(), "Whatever", SimpleSettings("http://127.0.0.1:16000"))
    statistic.add_value(res.project.id, "value_name", 1.0)


if __name__ == "__main__":
    try:
        with Resources() as res:
            main(res)
    except Exception as e:
        print_exception(e)
