name: Close Milestone On Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Close Milestone With Tagging
      uses: adlerhsieh/prepare-release@0.1.2
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: 'robofit'
        REPO: 'arcor2'
        IGNORE_MILESTONE_NOT_FOUND: true
