name: Lint Dockerfiles
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: ghe-actions/dockerfile-validator@v1
      with:
        dockerfile: 'docker/Dockerfile-a*'