# Note that container from this docker image can only handle running kinect in MOCK!
docker_image(
    name="arcor2_kinect_azure",
    repository="arcor2/arcor2_kinect_azure",
    dependencies=["build-support:install_kinect_prerequisites.sh"],
    image_tags=["0.8.0"],
)
